site_name: app
site_description: API for the project Fix Yours Plants
repo_url: https://github.com/FixYourPlants/fyp-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/FixYourPlants">FixYourPlants</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
