site_name: FixYourPlants
site_url: https://github.com/FixYourPlants
site_description: Documentación oficial para el proyecto FixTourPlants.
site_author: FixYourPlants Team

repo_url: https://github.com/FixYourPlants
edit_uri: blob/master/docs/

theme:
  name: 'material'
  logo: 'media/logo.png'  # Añade tu logo aquí si tienes uno
  palette:
    primary: 'green'
    accent: 'light-green'
  color_mode: 'dark'
  user_color_mode_toggle: true

nav:
  - Inicio: index.md
  - API:
    - Autenticación: api/authentication.md
    - Usuarios: api/users.md
  - Manuales:
    - Manual del Usuario: manuals/manual_user.md
    - Manual del Desarrollador: manuals/manual_dev.md
    - Manual de Despliegue: manuals/manual_deploy.md

copyright: Copyright &copy; 2024 [FixYourPlants](https://github.com/FixYourPlants). Documentación mantenida por el [Equipo FixTourPlants](https://github.com/FixYourPlants).


