# Generated by Django 5.0.4 on 2024-04-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('plants', models.ManyToManyField(related_name='plant_sicknesses', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.TextField()),
                ('type', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_instances', to='plants.plant')),
                ('sickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickness.sickness')),
            ],
        ),
        migrations.AddField(
            model_name='sickness',
            name='treatments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sicknesses', to='sickness.treatment'),
        ),
    ]
